# Generated by Django 3.1.2 on 2021-06-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210607_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproductposition',
            options={'ordering': ['-quantity'], 'verbose_name': 'Позиция в заказе', 'verbose_name_plural': 'Позиции в заказе'},
        ),
    ]
